# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Laravel.gitlab-ci.yml

stages:
  - test
  - deploy

image: php:latest

cache:
  paths:
    - vendor/

# test:
#   stage: test
  
#   only:
#     - master
  
#   script:
#     - apt-get update -yqq
#     - apt-get install git libcurl4-gnutls-dev libicu-dev libmcrypt-dev libvpx-dev libjpeg-dev libpng-dev libxpm-dev zlib1g-dev libfreetype6-dev libxml2-dev libexpat1-dev libbz2-dev libgmp3-dev libldap2-dev unixodbc-dev libpq-dev libsqlite3-dev libaspell-dev libsnmp-dev libpcre3-dev libtidy-dev -yqq
    
#     - curl -sS https://getcomposer.org/installer | php
#     - php composer.phar install
    
#     - php vendor/bin/phpunit --coverage-text --colors=never

deploy:
  stage: deploy

  only:
    - master
  
  before_script:
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    # - eval $(ssh-agent -s)
    - chmod 400 $SSH_PRIVATE_KEY

  script:
    - ssh -o StrictHostKeyChecking=no arsalan@116.203.84.245 -p 1997 -i $SSH_PRIVATE_KEY "
      ls &&
      echo 'gitlab runner' > .log"
