# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Laravel.gitlab-ci.yml

image: php:latest

cache:
  paths:
    - vendor/

before_script:
  # - apt-get update -yqq
  # - apt-get install git nodejs libcurl4-gnutls-dev libicu-dev libmcrypt-dev libvpx-dev libjpeg-dev libpng-dev libxpm-dev zlib1g-dev libfreetype6-dev libxml2-dev libexpat1-dev libbz2-dev libgmp3-dev libldap2-dev unixodbc-dev libpq-dev libsqlite3-dev libaspell-dev libsnmp-dev libpcre3-dev libtidy-dev -yqq
  - curl -sS https://getcomposer.org/installer | php
  - php composer.phar install

test:
  script:
    - php vendor/bin/phpunit --coverage-text --colors=never
